{{- $name := .Values.fullnameOverride | default .Release.Name }}
# =============================================================================
# SecretProviderClass — pulls TLS cert + key from AKV
# Mounts directly at /vault/tls as vault.crt and vault.key
# =============================================================================
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ $name }}-kv-secrets
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.keyvault.clientID }}"
    keyvaultName: "{{ .Values.keyvault.name }}"
    tenantId: "{{ .Values.keyvault.tenantId }}"
    objects: |
      array:
        - |
          objectName: VAULT-TLS-CERT
          objectType: secret
          objectAlias: vault.crt
        - |
          objectName: VAULT-TLS-KEY
          objectType: secret
          objectAlias: vault.key
