trigger: none

pool:
  name: <<YOUR AGENT POOL>>

#--------------------------
# Parameters
#--------------------------
parameters:
- name: ServiceConnection
  displayName: 'ServiceConnection details'
  type: string
  default: 'sc-dpn-dev-001'
  values:
    - sc-dpn-dev-001
    - sc-dpn-dev-002
    - sc-dpn-test-001
    - sc-dpn-test-002
    - sc-dpn-pdev-ppd-001
    - sc-dpn-ptest-ppd-001
    - sc-dpn-puat-ppd-001
- name: environment
  displayName: Environment Name
  type: string
  default: 'dev'
  values:
    - dev
    - devtest
    - test
    - pdev
    - ptest
    - puat
- name: cluster
  type: string
  default: dpn01
  displayName: "Target DPN Cluster (pdev/ptest/puat have only one DPN — dpn02 is disabled for those environments)"
  values:
    - dpn01
    - dpn02
# - name: enablePIT
#   type: boolean
#   default: false
#   displayName: Enable PIT Mutation Tests

#--------------------------
# Variables
#--------------------------
variables:
- group: dockerhub-creds
- group: federator-ci

- name: CLIENT_IMAGE
  value: dpn-federator-client

- name: SERVER_IMAGE
  value: dpn-federator-server

- name: IMAGE_TAG
  value: $(Build.BuildId)

- name: PARAMETERS_FILE
  value: .pipelines/azure-pipelines/config/${{ parameters.environment }}-${{ parameters.cluster }}.json

- name: CLOC_EXCLUDES
  value: "target,.git,node_modules"

#--------------------------
# Stages
#--------------------------

# =====================================================
# Stage 1 — Checkmarx
# =====================================================
stages:
- stage: CheckMarx_Scan
  displayName: CheckMarx One Scan
  jobs:
  - job: Scan
    steps:
    - template: ./CxOneScan.yml
      parameters:
        scanType: 'iac'
        cxoneserviceName: 'cxone-neso-DSI-devops'
        cxoneProjectName: 'NESO/DPN-Federator'
        cxoneProjectGroup: 'AZ-APP-CheckmarxOne-NESO'
        cxoneTenantName: 'nationalgrid'
        excludeFolders: '!.github'
        appName: 'dpn-federator-gateway'

# =====================================================
# Stage 2 — Unit Tests + Sonar
# =====================================================
- stage: UnitTests
  displayName: Run Unit Tests
  jobs:
  - job: RunTests
    displayName: Maven Unit Tests
    steps:
    - checkout: self

    - script: |
        echo "Loading config: $(PARAMETERS_FILE)"
        for param in $(jq -r 'keys_unsorted | .[]' "$(Build.SourcesDirectory)/$(PARAMETERS_FILE)"); do
          value=$(jq -r ".\"$param\"" "$(Build.SourcesDirectory)/$(PARAMETERS_FILE)")
          echo "##vso[task.setvariable variable=$param]$value"
        done
      displayName: Load Environment Config

    - task: JavaToolInstaller@0
      displayName: Set Java 21
      inputs:
        versionSpec: '21'
        jdkArchitectureOption: x64
        jdkSourceOption: PreInstalled

    - script: |
        mkdir -p ~/.m2
        cat <<EOF > ~/.m2/settings.xml
        <settings>
          <servers>
            <server>
              <id>github</id>
              <username>${GITHUB_MAVEN_USERNAME}</username>
              <password>${GITHUB_MAVEN_TOKEN}</password>
            </server>
          </servers>
        </settings>
        EOF
      displayName: Configure Maven settings

    - script: |
        echo "$(DOCKERHUB_PASSWORD)" | docker login -u "$(DOCKERHUB_USERNAME)" --password-stdin
      displayName: DockerHub login

    - task: Maven@4
      displayName: Run mvn clean verify
      inputs:
        mavenPomFile: pom.xml
        goals: clean verify
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/*.xml'

    # - script: |
    #     export MAVEN_OPTS="--add-opens=java.base/java.lang=ALL-UNNAMED \
    #     --add-opens=java.base/java.util=ALL-UNNAMED \
    #     --add-opens=java.base/java.io=ALL-UNNAMED \
    #     --add-opens=java.base/java.nio=ALL-UNNAMED \
    #     --add-opens=java.base/java.lang.reflect=ALL-UNNAMED -Xmx2048m"
    #     mvn org.pitest:pitest-maven:mutationCoverage
    #   displayName: Run PIT Mutation Tests
    #   condition: and(succeeded(), ${{ parameters.enablePIT }})

    # Install CLOC
    - script: |
        sudo apt-get update
        sudo apt-get install -y cloc
      displayName: Install CLOC

    # Run CLOC (JSON)
    - script: |
        echo "Running CLOC analysis..."
        cloc . --exclude-dir=$(CLOC_EXCLUDES) \
        --json --out=cloc-report.json

        echo "CLOC Summary:"
        cloc . --exclude-dir=$(CLOC_EXCLUDES)
      displayName: 'Run CLOC (JSON)'

    # Run CLOC (XML)
    - script: |
        echo "Running CLOC analysis..."
        cloc . --exclude-dir=$(CLOC_EXCLUDES) \
        --xml --out=cloc-report.xml

        echo "CLOC Summary:"
        cloc . --exclude-dir=$(CLOC_EXCLUDES)
      displayName: 'Run CLOC (XML)'

    - script: |
        echo "Copying CLOC reports to staging directory..."
        mkdir -p $(Build.ArtifactStagingDirectory)/cloc-reports

        ls -l cloc-report.*

        cp cloc-report.xml $(Build.ArtifactStagingDirectory)/cloc-reports
        cp cloc-report.json $(Build.ArtifactStagingDirectory)/cloc-reports
      displayName: 'Prepare CLOC artifacts'

    # THIS enables Code Coverage in Azure DevOps
    - task: PublishCodeCoverageResults@2
      displayName: Publish JaCoCo Coverage
      inputs:
        codeCoverageTool: JaCoCo
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/target/site/jacoco/jacoco.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/target/site/jacoco'
        failIfCoverageEmpty: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish JUnit Reports Folder'
      inputs:
        targetPath: target/surefire-reports/
        artifact: JUnit-reports

    # # Publish PIT Report
    # - task: PublishBuildArtifacts@1
    #   displayName: 'Publish PIT Report'
    #   condition: and(succeeded(), ${{ parameters.enablePIT }})
    #   inputs:
    #     PathtoPublish: 'target/pit-reports'
    #     ArtifactName: 'pit-report'        

    # Publish CLOC report
    - task: PublishBuildArtifacts@1
      displayName: 'Publish CLOC Report'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)/cloc-reports'
        artifactName: 'cloc-reports'

    # Publish SBOM File
    - script: |
        mkdir sbom-output
        cp target/*-sbom.json sbom-output/
        ls -l sbom-output/
      displayName: Copy SBOM file

    - task: PublishPipelineArtifact@1
      displayName: Publish SBOM
      inputs:
        targetPath: sbom-output
        artifact: SBOM

    # SonarQube Config
    - task: DownloadSecureFile@1
      name: sonarCert
      inputs:
        secureFile: sonarcert.pem
      displayName: 'Download SonarQube Cert'

    - bash: |
        echo "##vso[task.setvariable variable=NODE_EXTRA_CA_CERTS]$(sonarCert.secureFilePath)"
      displayName: "Set NODE CA certs"

    # Read secret from AKV
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: '${{ parameters.ServiceConnection }}'
        keyVaultName: '$(KEY_VAULT_NAME)'
        secretsFilter: 'SONAR-KEYSTORE-PWD'
        RunAsPreJob: false
      displayName: 'Get SonarQube Keystore Password'

    - script: |
        keytool -import -trustcacerts \
          -file $(sonarCert.secureFilePath) \
          -keystore $(Agent.TempDirectory)/sonar-truststore.jks \
          -storepass $(SONAR-KEYSTORE-PWD) \
          -alias sonarqube \
          -noprompt
      displayName: Import SonarQube Certs

    - task: SonarQubePrepare@7
      displayName: 'Prepare SonarQube Analysis'
      inputs:
        SonarQube: sonar-neso-sc
        scannerMode: CLI
        configMode: manual
        cliProjectKey: $(Build.Repository.Name) # Change as needed
        cliProjectName: $(Build.Repository.Name)
        cliSources: .
        extraProperties: |
          sonar.sources=src
          sonar.java.binaries=target/classes
          sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
          sonar.scanner.skipCertificateCheck=true

    - task: SonarQubeAnalyze@7
      displayName: 'Sonar Scan task'
      env:
        SONAR_SCANNER_OPTS: '-Djavax.net.ssl.trustStore=$(Agent.TempDirectory)/sonar-truststore.jks -Djavax.net.ssl.trustStorePassword=$(SONAR-KEYSTORE-PWD)'
      inputs:
        jdkversion: 'JAVA_HOME'

    - task: SonarQubePublish@7
      displayName: 'Publish SonarQube Results'
      inputs:
        pollingTimeoutSec: '600'

# =====================================================
# Stage 3 — Build + Push + Sign + Scan
# =====================================================
- stage: Build
  dependsOn: UnitTests
  condition: succeeded()

  jobs:
  - job: BuildImages
    timeoutInMinutes: 25
    steps:
    - checkout: self

    - script: |
        echo "Loading config: $(PARAMETERS_FILE)"
        for param in $(jq -r 'keys_unsorted | .[]' "$(Build.SourcesDirectory)/$(PARAMETERS_FILE)"); do
          value=$(jq -r ".\"$param\"" "$(Build.SourcesDirectory)/$(PARAMETERS_FILE)")
          echo "##vso[task.setvariable variable=$param]$value"
        done
      displayName: Load Environment Config

    - task: AzureCLI@2
      displayName: Login ACR
      inputs:
        azureSubscription: ${{ parameters.ServiceConnection }}
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az acr login --name $(CONTAINER_REGISTRY)

    # Build client
    - script: |
        docker build \
          --build-arg BASE_REGISTRY=$(BASE_REGISTRY) \
          --build-arg GITHUB_MAVEN_USERNAME=$(GITHUB_MAVEN_USERNAME) \
          --build-arg GITHUB_MAVEN_TOKEN=$(GITHUB_MAVEN_TOKEN) \
          -f Dockerfile.client \
          -t $(CONTAINER_REGISTRY_URL)/$(CLIENT_IMAGE):$(IMAGE_TAG) .
      displayName: Build Client Image

    # Build server
    - script: |
        docker build \
          --build-arg BASE_REGISTRY=$(BASE_REGISTRY) \
          --build-arg GITHUB_MAVEN_USERNAME=$(GITHUB_MAVEN_USERNAME) \
          --build-arg GITHUB_MAVEN_TOKEN=$(GITHUB_MAVEN_TOKEN) \
          -f Dockerfile.server \
          -t $(CONTAINER_REGISTRY_URL)/$(SERVER_IMAGE):$(IMAGE_TAG) .
      displayName: Build Images

    - script: |
        docker push $(CONTAINER_REGISTRY_URL)/$(CLIENT_IMAGE):$(IMAGE_TAG)
        docker push $(CONTAINER_REGISTRY_URL)/$(SERVER_IMAGE):$(IMAGE_TAG)
      displayName: Tag and Push Images

    #-----------------------------------------
    # Image Signing with Sigstore/Cosign
    #-----------------------------------------
    
    # Capture image digest
    - script: |
        CLIENT_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $(CONTAINER_REGISTRY_URL)/$(CLIENT_IMAGE):$(IMAGE_TAG))
        SERVER_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $(CONTAINER_REGISTRY_URL)/$(SERVER_IMAGE):$(IMAGE_TAG))

        echo $CLIENT_DIGEST > client-image-digest.txt
        echo $SERVER_DIGEST > server-image-digest.txt

        echo "##vso[task.setvariable variable=CLIENT_IMAGE_DIGEST]$CLIENT_DIGEST"
        echo "##vso[task.setvariable variable=SERVER_IMAGE_DIGEST]$SERVER_DIGEST"
        echo "Server Image Digest: $SERVER_DIGEST"
        echo "Client Image Digest: $CLIENT_DIGEST"

      displayName: Capture Image Digest

    # Download cosign key
    - task: DownloadSecureFile@1
      name: cosignKey
      inputs:
        secureFile: cosign.key
      displayName: 'Download Cosign Key'

    # Install Cosign binary
    - script: |
        curl -sSL https://github.com/sigstore/cosign/releases/latest/download/cosign-linux-amd64 -o cosign
        chmod +x cosign
        sudo mv cosign /usr/local/bin/
      displayName: Install Cosign

    # Read secret from AKV
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: '${{ parameters.ServiceConnection }}'
        keyVaultName: '$(KEY_VAULT_NAME)'
        secretsFilter: 'COSIGN-PASSWORD'
        RunAsPreJob: false

    # Sign the image with cosign
    - script: |
        cat > /tmp/signing-config.json << 'EOF'
        {
          "mediaType": "application/vnd.dev.sigstore.signingconfig.v0.2+json",
          "caUrls": [],
          "oidcUrls": [],
          "rekorTlogUrls": [],
          "tsaUrls": []
        }
        EOF
        cosign sign --key $(cosignKey.secureFilePath) --signing-config /tmp/signing-config.json $(CLIENT_IMAGE_DIGEST)        
        cosign sign --key $(cosignKey.secureFilePath) --signing-config /tmp/signing-config.json $(SERVER_IMAGE_DIGEST)
      env:
        COSIGN_PASSWORD: $(COSIGN-PASSWORD)
      displayName: Sign Images

    #  Publish the client digest file as an artifact
    - publish: client-image-digest.txt
      artifact: client-image-digest
      displayName: Publish Client Digest File
      # overwriteExistingArtifacts: true

    #  Publish the server digest file as an artifact
    - publish: server-image-digest.txt
      artifact: server-image-digest
      displayName: Publish Server Digest File
      # overwriteExistingArtifacts: true

    # ---------------------------------------
    # JFrog X-Ray Set Up
    # ---------------------------------------
    - task: DownloadSecureFile@1
      displayName: Jfrog Certificate Installation
      name: caCertificate
      inputs:
        secureFile: <<your specific value>>.crt
        retryCount: '1'
      enabled: true

    - script: |
        sudo chown root:root $(caCertificate.secureFilePath)
        sudo chmod a+r $(caCertificate.secureFilePath)
        sudo ln -s -f -t /etc/ssl/certs/ $(caCertificate.secureFilePath)
        sudo cp $(caCertificate.secureFilePath) /usr/share/ca-certificates/
        sudo apt-get -y install zip
      enabled: true
      displayName: Install JFrog Certificate

    # ---------------------------------------
    #  X-Ray Scan client Image
    # ---------------------------------------
    - task: JFrogDocker@1
      displayName: JFrog X-Ray Scan - client-container
      inputs:
        command: Scan
        xrayConnection: Jfrog_Xray_SC
        imageName: '$(CONTAINER_REGISTRY_URL)/$(CLIENT_IMAGE):$(IMAGE_TAG)'
        watchesSource: 'none'
        licenses: false
        allowBypassArchiveLimits: false
        threads: '3'
        skipLogin: true
        allowFailBuild: true

    # ---------------------------------------
    #  X-Ray Scan server Image
    # ---------------------------------------
    - task: JFrogDocker@1
      displayName: JFrog X-Ray Scan - server-container
      inputs:
        command: Scan
        xrayConnection: Jfrog_Xray_SC
        imageName: '$(CONTAINER_REGISTRY_URL)/$(SERVER_IMAGE):$(IMAGE_TAG)'
        watchesSource: 'none'
        licenses: false
        allowBypassArchiveLimits: false
        threads: '3'
        skipLogin: true
        allowFailBuild: true

    # ---------------------------------------
    #  Clean-Up Activity
    # ---------------------------------------
    - script: |
        echo "Cleaning up Docker images created by pipeline..."
        docker rmi $(CONTAINER_REGISTRY_URL)/$(CLIENT_IMAGE):$(IMAGE_TAG) || true
        docker rmi $(CONTAINER_REGISTRY_URL)/$(SERVER_IMAGE):$(IMAGE_TAG) || true
      displayName: Cleanup Docker & Temp Files
      condition: always()
