{{- if .Values.keyvault.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dpn-certificate-manager-kv-secrets
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "{{ .Values.keyvault.clientID }}"
    keyvaultName: "{{ .Values.keyvault.name }}"
    tenantId: "{{ .Values.keyvault.tenantId }}"
    objects: |
      array:
        - |
          objectName: MTLS-KEYSTORE-PASSWORD
          objectType: secret
        - |
          objectName: MTLS-TRUSTSTORE-PASSWORD
          objectType: secret
        - |
          objectName: VAULT-TOKEN
          objectType: secret
        - |
          objectName: OAUTH2-CLIENT-SECRET
          objectType: secret
        - |
          objectName: AZURE-STORAGE-ACCOUNT-NAME
          objectType: secret
        - |
          objectName: AZURE-STORAGE-ACCOUNT-KEY
          objectType: secret
        - |
          objectName: VAULT-TRUSTSTORE-PASSWORD
          objectType: secret
  secretObjects:
    # Certificate Manager app secrets
    - secretName: certificate-manager-secrets
      type: Opaque
      data:
        - objectName: MTLS-KEYSTORE-PASSWORD
          key: MTLS_KEYSTORE_PASSWORD
        - objectName: MTLS-TRUSTSTORE-PASSWORD
          key: MTLS_TRUSTSTORE_PASSWORD
        - objectName: VAULT-TOKEN
          key: VAULT_TOKEN
        - objectName: OAUTH2-CLIENT-SECRET
          key: OAUTH2_CLIENT_SECRET
        - objectName: VAULT-TRUSTSTORE-PASSWORD
          key: SPRING_CLOUD_VAULT_SSL_TRUST_STORE_PASSWORD
    # Azure file share secret (separate so it matches exact kubectl create format)
    - secretName: azure-fileshare-secret
      type: Opaque
      data:
        - objectName: AZURE-STORAGE-ACCOUNT-NAME
          key: azurestorageaccountname
        - objectName: AZURE-STORAGE-ACCOUNT-KEY
          key: azurestorageaccountkey
{{- end }}